site_name: Bedrock Configurator

nav:
  - Home: index.md
  - Current Configs: configs.md

markdown_extensions:
  - abbr
  - attr_list
  - def_list

extra_css:
  - css/extra.css

repo_url: https://github.com/mozmeao/www-config
edit_uri: ""
