# https://kubernetes.io/docs/admin/authorization/rbac/#rolebinding-and-clusterrolebinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: git-sync-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - services
  - services/proxy
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/rollback
  - deployments/scale
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions
  resources:
  - deployments
  - deployments/rollback
  - deployments/scale
  - ingresses
  - replicasets
  - replicasets/scale
  - replicationcontrollers/scale
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mozilla.org
  resources:
  - versions
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - voyager.appscode.com
  resources:
  - ingresses
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bedrock-demo-git-sync-operator
  namespace: bedrock-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grant-git-sync-operator-access
  namespace: bedrock-demo
subjects:
- kind: ServiceAccount
  name: bedrock-demo-git-sync-operator
  namespace: bedrock-demo
roleRef:
  kind: ClusterRole
  name: git-sync-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bedrock-dev-git-sync-operator
  namespace: bedrock-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grant-git-sync-operator-access
  namespace: bedrock-dev
subjects:
- kind: ServiceAccount
  name: bedrock-dev-git-sync-operator
  namespace: bedrock-dev
roleRef:
  kind: ClusterRole
  name: git-sync-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bedrock-stage-git-sync-operator
  namespace: bedrock-stage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grant-git-sync-operator-access
  namespace: bedrock-stage
subjects:
- kind: ServiceAccount
  name: bedrock-stage-git-sync-operator
  namespace: bedrock-stage
roleRef:
  kind: ClusterRole
  name: git-sync-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bedrock-prod-git-sync-operator
  namespace: bedrock-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grant-git-sync-operator-access
  namespace: bedrock-prod
subjects:
- kind: ServiceAccount
  name: bedrock-prod-git-sync-operator
  namespace: bedrock-prod
roleRef:
  kind: ClusterRole
  name: git-sync-operator
  apiGroup: rbac.authorization.k8s.io
