apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: bedrock-dev
    type: web
  name: bedrock-dev-web
  namespace: bedrock-dev
  selfLink: /apis/extensions/v1beta1/namespaces/bedrock-dev/deployments/bedrock-dev-web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bedrock-dev
      type: web
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bedrock-dev
        type: web
      name: bedrock-dev-web
      namespace: bedrock-dev
    spec:
      containers:
      - args:
        - ./bin/run.sh
        command:
        - /bin/bash
        - -c
        env:
        - name: ALLOWED_HOSTS
          value: "*"
        - name: AWS_DB_S3_BUCKET
          value: bedrock-db-dev
        - name: BASKET_URL
          value: https://basket.allizom.org
        - name: CSP_REPORT_ENABLE
          value: "True"
        - name: DEBUG
          value: "False"
        - name: DEV
          value: "True"
        - name: DISABLE_SSL
          value: "False"
        - name: ENABLE_CSP_MIDDLEWARE
          value: "True"
        - name: ENABLE_HOSTNAME_MIDDLEWARE
          value: "True"
        - name: FUNNELCAKE_101_LOCALES
          value: en-US
        - name: FUNNELCAKE_101_PLATFORMS
          value: win
        - name: FUNNELCAKE_102_LOCALES
          value: en-US
        - name: FUNNELCAKE_102_PLATFORMS
          value: win
        - name: FUNNELCAKE_103_LOCALES
          value: de
        - name: FUNNELCAKE_103_PLATFORMS
          value: win
        - name: FUNNELCAKE_104_LOCALES
          value: de
        - name: FUNNELCAKE_104_PLATFORMS
          value: win
        - name: HTTPS
          value: "on"
        - name: L10N_CRON
          value: "True"
        - name: LOGLEVEL
          value: info
        - name: MOFO_SECURITY_ADVISORIES_BRANCH
          value: testing
        - name: MOFO_SECURITY_ADVISORIES_PATH
          value: /tmp/mofo_security_advisories
        - name: PROD
          value: "True"
        - name: RUN_SUPERVISOR
          value: "True"
        - name: SECURE_BROWSER_XSS_FILTER
          value: "True"
        - name: SECURE_SSL_REDIRECT
          value: "True"
        - name: SWITCH_NEWSLETTER_MAINTENANCE_MODE
          value: "False"
#TODO
#        - name: BASKET_API_KEY
#          valueFrom:
#            secretKeyRef:
#              key: basket-api-key
#              name: bedrock-dev-v198-env
#        - name: EMAIL_HOST
#          valueFrom:
#            secretKeyRef:
#              key: email-host
#              name: bedrock-dev-v198-env
#        - name: EMAIL_HOST_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              key: email-host-password
#              name: bedrock-dev-v198-env
#        - name: EMAIL_HOST_USER
#          valueFrom:
#            secretKeyRef:
#              key: email-host-user
#              name: bedrock-dev-v198-env
#        - name: EMAIL_PORT
#          valueFrom:
#            secretKeyRef:
#              key: email-port
#              name: bedrock-dev-v198-env
#        - name: EMAIL_USE_TLS
#          valueFrom:
#            secretKeyRef:
#              key: email-use-tls
#              name: bedrock-dev-v198-env
#        - name: NEWRELIC_APP_ID
#          valueFrom:
#            secretKeyRef:
#              key: newrelic-app-id
#              name: bedrock-dev-v198-env
#        - name: NEWRELIC_BROWSER_LICENSE_KEY
#          valueFrom:
#            secretKeyRef:
#              key: newrelic-browser-license-key
#              name: bedrock-dev-v198-env
#        - name: NEWRELIC_PYTHON_INI_FILE
#          valueFrom:
#            secretKeyRef:
#              key: newrelic-python-ini-file
#              name: bedrock-dev-v198-env
#        - name: NEW_RELIC_APP_NAME
#          valueFrom:
#            secretKeyRef:
#              key: new-relic-app-name
#              name: bedrock-dev-v198-env
#        - name: NEW_RELIC_LICENSE_KEY
#          valueFrom:
#            secretKeyRef:
#              key: new-relic-license-key
#              name: bedrock-dev-v198-env
#        - name: OPTIMIZELY_PROJECT_ID
#          valueFrom:
#            secretKeyRef:
#              key: optimizely-project-id
#              name: bedrock-dev-v198-env
#        - name: SECRET_KEY
#          valueFrom:
#            secretKeyRef:
#              key: secret-key
#              name: bedrock-dev-v198-env
#        - name: SENTRY_DSN
#          valueFrom:
#            secretKeyRef:
#              key: sentry-dsn
#              name: bedrock-dev-v198-env
#        - name: TWITTER_ACCESS_TOKEN
#          valueFrom:
#            secretKeyRef:
#              key: twitter-access-token
#              name: bedrock-dev-v198-env
#        - name: TWITTER_ACCESS_TOKEN_SECRET
#          valueFrom:
#            secretKeyRef:
#              key: twitter-access-token-secret
#              name: bedrock-dev-v198-env
#        - name: TWITTER_CONSUMER_KEY
#          valueFrom:
#            secretKeyRef:
#              key: twitter-consumer-key
#              name: bedrock-dev-v198-env
#        - name: TWITTER_CONSUMER_SECRET
#          valueFrom:
#            secretKeyRef:
#              key: twitter-consumer-secret
#              name: bedrock-dev-v198-env
        image: mozorg/bedrock:master-592da1516af5a625d51a322d534005e866b8e89a
        imagePullPolicy: IfNotPresent
        name: bedrock-dev-web
        ports:
          - containerPort: 8000
        readinessProbe:
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
          httpGet:
            path: /readiness/
            scheme: HTTP
            port: 8000
        resources:
          limits:
            cpu: 500m
            memory: 300Mi
          requests:
            cpu: 250m
            memory: 120Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
