apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: bedrock-dev
    type: web
  name: bedrock-dev-web
  namespace: bedrock-dev
  selfLink: /apis/autoscaling/v1/namespaces/bedrock-dev/horizontalpodautoscalers/bedrock-dev-web
spec:
  maxReplicas: 6
  minReplicas: 3
  scaleTargetRef:
    kind: Deployment
    name: bedrock-dev-web
  targetCPUUtilizationPercentage: 80
