apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: bedrock-stage
    type: web
  name: bedrock-stage-web
  namespace: bedrock-stage
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bedrock-stage
      type: web
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bedrock-stage
        type: web
      name: bedrock-stage-web
      namespace: bedrock-stage
    spec:
      containers:
      - args:
        - ./bin/run.sh
        command:
        - /bin/bash
        - -c
        env:
        - name: ALLOWED_HOSTS
          value: "*"
        - name: AWS_DB_S3_BUCKET
          value: bedrock-db-stage
        - name: BASKET_URL
          value: https://basket.allizom.org
        - name: CSP_REPORT_ENABLE
          value: "True"
        - name: DEBUG
          value: "False"
        - name: DEV
          value: "False"
        - name: DISABLE_SSL
          value: "False"
        - name: ENABLE_CSP_MIDDLEWARE
          value: "True"
        - name: ENABLE_HOSTNAME_MIDDLEWARE
          value: "True"
        - name: HTTPS
          value: "on"
        - name: L10N_CRON
          value: "True"
        - name: LOGLEVEL
          value: info
        - name: MOFO_SECURITY_ADVISORIES_PATH
          value: /tmp/mofo_security_advisories
        - name: PROD
          value: "True"
        - name: RUN_SUPERVISOR
          value: "True"
        - name: SECURE_BROWSER_XSS_FILTER
          value: "True"
        - name: SECURE_SSL_REDIRECT
          value: "True"
        - name: SWITCH_NEWSLETTER_MAINTENANCE_MODE
          value: "False"
        - name: BASKET_API_KEY
          valueFrom:
            secretKeyRef:
              key: basket-api-key
              name: bedrock-stage-secrets
        - name: EMAIL_HOST
          valueFrom:
            secretKeyRef:
              key: email-host
              name: bedrock-stage-secrets
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              key: email-host-password
              name: bedrock-stage-secrets
        - name: EMAIL_HOST_USER
          valueFrom:
            secretKeyRef:
              key: email-host-user
              name: bedrock-stage-secrets
        - name: EMAIL_PORT
          valueFrom:
            secretKeyRef:
              key: email-port
              name: bedrock-stage-secrets
        - name: EMAIL_USE_TLS
          valueFrom:
            secretKeyRef:
              key: email-use-tls
              name: bedrock-stage-secrets
        - name: NEWRELIC_PYTHON_INI_FILE
          value: newrelic.ini
        - name: NEW_RELIC_APP_NAME
          valueFrom:
            configMapKeyRef:
              name: bedrock-stage-configmap
              key: NEW_RELIC_APP_NAME
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              key: new-relic-license-key
              name: bedrock-stage-secrets
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret-key
              name: bedrock-stage-secrets
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              key: sentry-dsn
              name: bedrock-stage-secrets
        - name: STD_SMS_COUNTRIES_DESKTOP
          value: US,DE,FR
        - name: STD_SMS_COUNTRIES_WHATSNEW50
          value: US,DE,FR
        - name: STD_SMS_COUNTRIES_WHATSNEW61
          value: US,DE
        - name: STUB_ATTRIBUTION_HMAC_KEY
          valueFrom:
            secretKeyRef:
              key: stub-attribution-hmac-key
              name: bedrock-stage-secrets
        - name: STUB_ATTRIBUTION_RATE
          value: '1'
        - name: SWITCH_TRACKING_PIXEL
          value: 'on'
        - name: TWITTER_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              key: twitter-access-token
              name: bedrock-stage-secrets
        - name: TWITTER_ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              key: twitter-access-token-secret
              name: bedrock-stage-secrets
        - name: TWITTER_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              key: twitter-consumer-key
              name: bedrock-stage-secrets
        - name: TWITTER_CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              key: twitter-consumer-secret
              name: bedrock-stage-secrets
        image: mozorg/bedrock:prod-75fa4f5dcc9fbeae7630adb470c3166e8cc197e7
        imagePullPolicy: IfNotPresent
        name: bedrock-stage-web
        ports:
          - containerPort: 8000
        readinessProbe:
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
          httpGet:
            path: /readiness/
            scheme: HTTP
            port: 8000
        resources:
          limits:
            cpu: 500m
            memory: 300Mi
          requests:
            cpu: 250m
            memory: 120Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
